### ISSUE TITLE
Was ist ein Sozial-Graph?

### ISSUE THREAD

**Issue by suchja** [tbsvttr/why-git#2]
@tbsvttr Habe nun im Netz nachgeschlagen was das ist. Falls du eine gute Erklärung kennst, könntest du noch einen Link darauf einfügen. Ansonsten finde ich den Artikel super!

DANKE!

**Comment by tbsvttr** [comment]
Erledigt mit https://github.com/tbsvttr/why-git/commit/f6916961b12ebe61012df2daf3ef6b8ff25271d4
